---
title: Publications
---


## Preprints / Submitted

- Deng, Y., **Wang, R.**, Zhan, X. (2026+). Randomized interventional effects for semicompeteting risks, with application to allogeneic stem cell transplantation study.  [arXiv](https://arxiv.org/abs/2412.06114)

- **Wang, R.**, Zhao, Y., Dukes, O., Zhang, B. (2026+). Nested Instrumental Variables Analysis: Switcher Average Treatment Effect, Identification, Efficient Estimation and Generalizability.  [arXiv](https://arxiv.org/abs/2405.07102)

- **Wang, R.**, Chan, KCG., Ye, T. (2026+). GMM with Many Weak Moment Conditions and Nuisance Parameters: General Theory and Applications to Causal Inference. [arXiv](https://arxiv.org/abs/2505.07295)

- Wang, Z., Sourial, N., **Wang, R.**, Bergman, H., Liu, X., Vedel, I. (2026+). Neo-Familist Values and Health-Seeking Behaviours Among Older Adults in Rural China: Evidence from China Longitudinal Aging Social Survey (CLASS). 


## Journal Articles / In Press


### 2026

1. **Wang, R.**, Heagerty, P., Chan, KCG., Suri, P. (2026). Estimating controlled direct treatment effects on pain intensity using structural mean models: a general approach for pain randomized controlled trials. Accepted at *Pain Reports*.

   
### 2025
1. Joshi, M. A., Manubolu, V. S., Kinninger, A., **Wang, R.**, McClelland, R. L., Roy, R. K., Budoff, M. J. (2025). Sex Differences in Aortic Arch Calcification with Zero Coronary Artery Calcium. *Heart, Lung and Circulation*. [DOI](https://doi.org/10.1016/j.hlc.2025.05.087)

   <details>
   <summary><strong>Abstract</strong></summary>

   **Background**
Studies have linked aortic calcification to an increased risk of all-cause mortality and cardiovascular mortality. There is minimal evidence evaluating the sex differences in the prevalence of aortic arch calcification (AAC) in relation to zero coronary artery calcium (CAC).
**Method**
This study included participants from the Multi-Ethnic Study of Atherosclerosis (MESA) exam 5, of which 2,564 underwent non-contrast chest computed tomography scans. We utilised the CAC and AAC scores measured by the Agatston method to evaluate sex differences in AAC among participants overall, and among those with zero CAC. Regression analysis was performed, adjusting for covariates, to evaluate the sex difference.
**Results**
The average age of the 2,564 participants was 69.2±9.2 years, 46% were women, 38% were White, 13% were Chinese, 27% were Black, and 22% were Hispanic/Latino. A total of 813 (32%) had a CAC of zero. The prevalence of AAC was higher in women than men, both in the zero CAC population (87% vs 80%) and overall (92% vs 90%). The median AAC was additionally higher in women in the overall population (217 vs 212) and in the CAC zero population (60 vs 20). After controlling for covariates, the estimated average AAC was 0.51 times lower in men than women (95% confidence interval 0.36–0.72; p<0.001) in the CAC zero population.
**Conclusions**
This study demonstrated that the prevalence of aortic arch calcium is higher in women compared to men. In a subset of the population with zero CAC, the average amount of AAC is significantly higher in women. In the future, event analysis should be done to determine whether these sex differences in AAC may partially explain the sex differences in the prediction of atherosclerotic cardiovascular disease events.

   </details>


1. Deng, Y., **Wang, R.** (2025). Adjusted Nelson–Aalen Estimators by Inverse Treatment Probability Weighting With an Estimated Propensity Score. *Statistics in Medicine*, 44: e70085. [DOI](https://doi.org/10.1002/sim.70085)

   <details>
   <summary><strong>Abstract</strong></summary>

   Inverse probability of treatment weighting (IPW) has been well applied in causal inference to estimate population-level estimands from observational studies. For time-to-event outcomes, the failure time distribution can be estimated by estimating the cumulative hazard in the presence of random right censoring. IPW can be performed by weighting the event counting process and at-risk process by the inverse treatment probability, resulting in an adjusted Nelson–Aalen estimator for the population-level counterfactual cumulative incidence function. We consider the adjusted Nelson–Aalen estimator with an estimated propensity score in the competing risks setting. When the estimated propensity score is regular and asymptotically linear, we derive the influence functions for the counterfactual cumulative hazard and cumulative incidence. Then we establish the asymptotic properties for the estimators. We show that the uncertainty in the estimated propensity score contributes to an additional variation in the estimators. However, through simulation and real-data application, we find that such an additional variation is usually small.

   </details>

### 2024
1. Barforoshi, S., Manubolu, V. S., **Wang, R.**, McClelland, R. L., Budoff, M. J. (2024). Incremental value of ABI and CAC beyond traditional risk markers in long-term prediction of cardiovascular disease incidence in participants with diabetes and impaired fasting glucose: Multi-Ethnic Study of Atherosclerosis. *Atherosclerosis*, 117186. [DOI](https://doi.org/10.1016/j.atherosclerosis.2023.117186)

   <details>
   <summary><strong>Abstract</strong></summary>

   **Background and aims** Subclinical atherosclerosis (SA) diagnosis is key to primary prevention of atherosclerotic cardiovascular disease (ASCVD). SA is common among diabetics. Ankle brachial index (ABI) and coronary artery calcium (CAC) are markers of SA. This study examined whether adding ABI and CAC to diabetic individuals improved ASCVD risk prediction beyond established risk factors.
**Methods** 
MESA is an observational cohort of 6814 participants without clinical cardiovascular disease. All participants with diabetes and impaired fasting glucose were included in the analysis. The association between CAC, ABI, and incident ASCVD, and all-cause mortality was examined using Cox proportional hazard regression. The risk prediction models including ABI and/or CAC in addition to standard risk factors alone were compared.
**Results**
Of the 1719 participants, 55% were male and average age was 64 (±9.6) years old. Participants with diabetes or impaired fasting glucose with higher CAC and lower ABI had higher ASCVD and all-cause mortality. ABI and CAC enhanced ASCVD discrimination over standard risk factors, with C-index (95% CI) of 0.689 (0.66, 0.718) for risk factors alone, 0.696 (0.668, 0.724) for ABI, 0.719 (0.691, 0.747) for CAC, and 0.721 (0.693, 0.749) for CAC + ABI. Similarly, for all-cause mortality, both CAC and ABI improved risk discrimination in addition to standard risk factors alone.
**Conclusions**
In a large population-based study of individuals with diabetes or impaired fasting glucose, the addition of ABI and CAC to conventional risk factors improved 10-year ASCVD risk prediction. ABI and CAC are non-invasive and cost-effective tests; therefore, these markers should be included into ASCVD risk stratification for primary prevention in the diabetic and impaired fasting glucose population.

   </details>


1. Ichikawa, K., **Wang, R.**, McClelland, R. L., Manubolu, V. S., Susarla, S., Lee, D., Pourafkari, L., Fazlalizadeh, H., Aldana-Bitar, J., Robin, R., Kinninger, A., Roy, S. K., Post, W. S., Budoff, M. J. (2024). The prognostic value of thoracic aortic calcification comparison with coronary artery calcification. *Heart*. [DOI](https://doi.org/10.1136/heartjnl-2023-323838)

   <details>
   <summary><strong>Abstract</strong></summary>

   This study compared the prognostic value of quantified thoracic artery calcium (TAC) including aortic arch on chest CT and coronary artery calcium (CAC) score on ECG-gated cardiac CT.
**Methods** A total of 2412 participants who underwent both chest CT and ECG-gated cardiac CT at the same period were included in the Multi-Ethnic Study of Atherosclerosis Exam 5. All participants were monitored for incident atherosclerotic cardiovascular disease (ASCVD) events. TAC is defined as calcification in the ascending aorta, aortic arch and descending aorta on chest CT. The quantification of TAC was measured using the Agatston method. Time-dependent receiver-operating characteristic (ROC) curves were used to compare the prognostic value of TAC and CAC scores.
**Results** Participants were 69±9 years of age and 47% were male. The Spearman correlation between TAC and CAC scores was 0.46 (p<0.001). During the median follow-up period of 8.8 years, 234 participants (9.7%) experienced ASCVD events. In multivariable Cox regression analysis, TAC score was independently associated with increased risk of ASCVD events (HR 1.31, 95% CI 1.09 to 1.58) as well as CAC score (HR 1.82, 95% CI 1.53 to 2.17). However, the area under the time-dependent ROC curve for CAC score was greater than that for TAC score in all participants (0.698 and 0.641, p=0.031). This was particularly pronounced in participants with borderline/intermediate and high 10-year ASCVD risk scores.
**Conclusion** Our study demonstrated a significant association between TAC and CAC scores but a superior prognostic value of CAC score for ASCVD events. These findings suggest TAC on chest CT provides supplementary data to estimate ASCVD risk but does not replace CAC on ECG-gated cardiac CT.

   </details>

### 2022
1. **Wang, R.**, Wang, J., Hu, T., Zhou, X.-H. (2022). Population-Level Effectiveness of COVID-19 Vaccination Program in the United States: Causal Analysis Based on Structural Nested Mean Model. *Vaccines*. [DOI](https://doi.org/10.3390/vaccines10050726)

   <details>
   <summary><strong>Abstract</strong></summary>
   Though COVID-19 vaccines have shown high efficacy, real-world effectiveness at the population level remains unclear. Based on the longitudinal data on vaccination coverage and daily infection cases from fifty states in the United States from March to May 2021, causal analyses were conducted using structural nested mean models to estimate the population-level effectiveness of the COVID-19 vaccination program against infection with the original strain. We found that in the US, every 1% increase of vaccination coverage rate reduced the weekly growth rate of COVID-19 confirmed cases by 1.02% (95% CI: 0.26%, 1.69%), and the estimated population-level effectiveness of the COVID-19 program was 63.9% (95% CI: 18.0%, 87.5%). In comparison to a no-vaccination scenario, the COVID-19 vaccination campaign averted 8.05 million infections through the study period. Scenario analyses show that a vaccination program with doubled vaccination speed or with more rapid vaccination speed at the early stages of the campaign would avert more infections and increase vaccine effectiveness. The COVID-19 vaccination program demonstrated a high population-level effectiveness and significantly reduced the disease burden in the US. Accelerating vaccine rollout, especially at an early stage of the campaign, is crucial for reducing COVID-19 infections.

   

   </details>


### 2021
1. Deng, Y., Chen, F., Li, Y., Qian, K., **Wang, R.**, Zhou, X.-H. (2021). A powerful test for the maximum treatment effect in thorough QT/QTc studies. *Statistics in Medicine*, 40(8), 1947–1959. [DOI](https://doi.org/10.1002/sim.8881)

   <details>
   <summary><strong>Abstract</strong></summary>

   Parallel-group thorough QT/QTc studies focus on the change of QT/QTc values at several time-matched points from a pretreatment day (baseline) to a posttreatment day for different groups of treatment. The International Council for Harmonisation E14 stresses that QTc prolongation beyond a threshold represents high cardiac risk and calls for a test on the largest time-matched treatment effect (QTc prolongation). QT/QTc analysis usually assumes a jointly multivariate normal (MVN) distribution of pretreatment and posttreatment QT/QTc values, with a blocked compound symmetry covariance matrix. Existing methods use an analysis of covariance (ANCOVA) model including day-averaged baseline as a covariate to deal with the MVN model. However, the ANCOVA model tends to underestimate the variation of the estimator for treatment effects, resulting in the inflation of empirical type I error rate when testing whether the largest QTc prolongation is beyond a threshold. In this article, we propose two new methods to estimate the time-matched treatment effects under the MVN model, including maximum likelihood estimation and ordinary-least-square-based two-stage estimation. These two methods take advantage of the covariance structure and are asymptotically efficient. Based on these estimators, powerful tests for QT/QTc prolongation are constructed. Simulation shows that the proposed estimators have smaller mean square error, and the tests can control the type I error rate with high power. The proposed methods are applied on testing the carryover effect of diltiazem to inhibit dofetilide in a randomized phase 1 trial.

   </details>







